name: group7-0
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: no
          MYSQL_DATABASE: simplon_groupx_test
          MYSQL_PASSWORD: abcd
          MYSQL_USER: toto
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Populate MySQL Database
        run: bash pre-test.sh
      - run: npm install
      - run: npm run test
      - name: Send email
        uses: AlexisMateo/sendmail-action@5
        with:
          smtp-server: smtp.gmail.com
          smtp-server-port: 587
          auth-user: luca.harico@laposte.net
          auth-password: Testeur7!
          subject: mail to Totorico69
          body: test oki
          from: luca.harico@laposte.net
          to: luca.harico@laposte.net
          is-tls: false
          commit-message: true
