name: group7-0
description: [ push ]
jobs:
  test:
  name: Run tests
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@dev
    - uses: actions/checkout@main
      with:
        node-version: '15'
    - run: npm install
    - run: npm test
