name: group7-0-deploy
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  deploy:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: garygrossgarten/github-action-ssh@release
        env:
          CLONE_DIR: /home/john/node-grp7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          command: |
            echo "start building"
            rm -rf $CLONE_DIR
            git clone git@github.com:jldjld/back.git $CLONE_DIR
            cd $CLONE_DIR
            npm install
            npm run build