name: group7-0-deploy
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  deploy:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          command: |
            echo "Hello World"
            echo "start building"
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '15'
      #   working-directory: ./node-grp7
      #   run: npm install
      #   run: npm run build