name: group7-0-deploy
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  deploy:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: garygrossgarten/github-action-ssh@release
        with:
          command: echo 'start deployment'
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          command: echo 'end deployment'
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '15'
      # - run: npm install
      # - run: npm run build